name: mezgebestore
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  numeric_keyboard: ^1.0.0
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flutter_spinkit: ^4.1.2
  firebase_database: ^3.1.6
  cached_network_image: any
  data_connection_checker: ^0.3.4
  connectivity: ^0.4.9
  intl_phone_field: ^1.3.0
  flutter_otp_text_field: ^0.0.1
  pin_code_fields: ^4.0.0
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.4
  photo_view: ^0.10.0
  rflutter_alert: ^1.0.3
  dotted_border: ^1.0.6
  shared_preferences: any
  geolocator: ^5.3.2+2
  flutter_map:
  google_maps_flutter: ^0.5.27+1
  location: ^2.3.5
  url_launcher: ^5.5.0
  geopoint: ^0.7.1
  geoflutterfire: any
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3
  transparent_image: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_slnt,wght.ttf
