name: mezgebestore
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  numeric_keyboard: 
  cupertino_icons:
  cloud_firestore:
  firebase_core:
  firebase_auth:
  modal_progress_hud:
  font_awesome_flutter:
  flutter_spinkit:
  firebase_database:
  cached_network_image: 2.0.0-rc
  mobx:
  flutter_mobx:
  provider:
  rflutter_alert:
  shared_preferences:
  location:
  google_maps_flutter:
  geopoint: 
  geoflutterfire:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:
  image_picker:
  firebase_storage:
  connection_status_bar:
  carousel_slider: ^3.0.0
#  day_night_switch: ^0.0.2+1
  day_night_switch:
  connectivity_wrapper:
  flutter_offline:
  connectivity_widget:
  connectivity:
  auto_size_text:


flutter:
  uses-material-design: true
  assets:
    - images/
    - i18n/am.json
    - i18n/en.json


  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_slnt,wght.ttf
